Init
rapidez/statamic-brands pull request #1
Opened 2022-11-08 08:08 UTC by jbclaudio

2022-11-08 08:17 UTC, royduin requested changes

2022-11-08 08:17 UTC, royduin commented on config/brands.php
> +    'brand_attribute_code' => env('BRAND_ATTRIBUTE_CODE', 'brand')
```suggestion
    'brand_attribute_code' => 'brand',
```

The `env()` is for variables which could be different on environments. This settings wouldn't. Don't forget to change the readme.

2022-11-08 08:17 UTC, royduin commented on README.md
> +```
```suggestion

The default attribute code used for brands is `brand`, but it is also possible that another attribute is used for this. You can change this in `config/statamic-brands.php`.
```

2022-11-08 08:17 UTC, royduin commented on src/ServiceProvider.php
> +        $this->mergeConfigFrom(__DIR__.'/../config/brands.php', 'brands');
```suggestion
        $this->mergeConfigFrom(__DIR__.'/../config/statamic-brands.php', 'statamic-brands');
```

2022-11-08 08:17 UTC, royduin commented on src/ServiceProvider.php
> +            __DIR__.'/../config/brands.php' => config_path('brands.php'),
```suggestion
            __DIR__.'/../config/statamic-brands.php' => config_path('statamic-brands.php'),
```

2022-11-10 14:40 UTC, indykoning commented on src/Actions/CreateBrands.php
> +        ])->each(fn ($brand) => Entry::updateOrCreate($brand, 'brands', 'brand_code', $storeCode));
My personal preference for code style on this is
```suggestion
        return $brands->filter(fn ($brand) => !blank($brand->name) && !blank($brand->brand_code))
            ->map(fn ($brand) => [
                'title' => $brand->title,
                'brand_code' => $brand->brand_code,
                'path' => $brand->brand_code
            ])
            ->each(fn ($brand) => Entry::updateOrCreate($brand, 'brands', 'brand_code', $storeCode));
```

2022-11-10 14:40 UTC, indykoning commented on src/Actions/DeleteBrands.php
> +        $deletedBrands->each(fn ($deletedBrand) => $deletedBrand->delete());
```suggestion
        $deletedBrands = Entry::whereCollection('brands')
            ->where('locale', $storeCode)
            ->filter(fn ($deletedBrand) => !$brandCodes->contains($deletedBrand->get('brand_code')))
            ->each(fn ($deletedBrand) => $deletedBrand->delete());
```

2022-11-10 14:49 UTC, merged

2022-11-10 14:55 UTC, BobWez98 commented on README.md
> +sites:
if brands get published, isn't this automaticly generated by statamic?

2022-11-10 14:55 UTC, BobWez98 commented on src/Events/BrandsImportedEvent.php
> +class BrandsImportedEvent
Where does this event get used?

2022-11-10 15:02 UTC, jbclaudio commented on README.md
> +sites:
No I had to add it manually after publishing

2022-11-10 15:02 UTC, jbclaudio commented on src/Events/BrandsImportedEvent.php
> +class BrandsImportedEvent
After the import this is dispatched

https://github.com/rapidez/statamic-brands/pull/1/files/2185e9c8bff29c65c47073894c033b21f246025e#diff-79dc63c8e2631568230453cefe52c8e3cbe1845c22e68c754b921660db579caaR56